export const ActionTypes = {
  MOVIES_LOADING: "MOVIES_LOADING", // YÜKLENMEYE BAŞLADIĞINDA LOADING
  MOVIES_SUCCESS: "MOVIES_SUCCESS", // BAŞARILI OLURSA SUCCESS
  MOVIES_ERROR: "MOVIES_ERROR", // BAŞARISIZ OLURSA ERROR
  GENRES_LOADING: "GENRES_LOADING",
  GENRES_ERROR: "GENRES_ERROR",
  GENRES_SUCCESS: "GENRES_SUCCESS",
};
